### ISSUE TITLE
Service generate with error

### ISSUE THREAD

**Issue by dschnare** [gradealabs/generator-feathers#4]
When calling the service generator and choosing `Y` when asked if the service requires authentication, the following error occurs:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:87:11)
    at Object.urlParse [as parse] (url.js:81:5)
    at ConnectionGenerator._getConfiguration (/Users/darren/Workspace/gradealabs/labs/generator-feathers/generators/connection/index.js
:46:24)
    at ConnectionGenerator._writeConfiguration (/Users/darren/Workspace/gradealabs/labs/generator-feathers/generators/connection/index.
js:103:32)
    at ConnectionGenerator.writing (/Users/darren/Workspace/gradealabs/labs/generator-feathers/generators/connection/index.js:293:10)
    at Object.<anonymous> (/Users/darren/Workspace/gradealabs/labs/generator-feathers/node_modules/yeoman-generator/lib/index.js:417:23
)
```

Steps to repro:
```
yo feathers:service
Knex adapter
PostgresSQL database
Y to authentication
```

**Comment by dschnare** [comment]
This doesn't occur when not requiring authentication for the created service. Also, tested with NeDB without authentication and it was fine.

**Comment by dschnare** [comment]
This was resolved by merging the latest upstream changes.
